"use client";
import {useEffect,useMemo,useState,useContext} from "react";
import type {ReactNode} from "react";
import {AlertTriangle,CalendarDays,Check,ChevronLeft,ChevronRight,CircleDollarSign,Home,Landmark,Pencil,Plus,RotateCcw,Settings,ShieldCheck,Trash2,TrendingUp,Wallet,X} from "lucide-react";
import {Asset,Debt,Expense,FinanceState,Income,Insurance,Investment,SavingGoal,Payment,MonthlySnapshot,emptyState} from "../lib/types";
import {assetMonthlyPlan,dateFor,ensureMonthlyPayments,goalProgress,goalMonthlyPlan,money,monthKey,monthsUntil,payoffDate,monthlyDebtPayment,payoffMonths,progress,totals} from "../lib/finance";
import { supabase } from "../lib/supabase";
import { HouseholdContext } from "./AuthGate";
const KEY="finflow-state-v4";
type Tab="dashboard"|"income"|"debt"|"assets"|"investments"|"expenses"|"savings"|"insurance"|"calendar"|"reports";
const tabs:[Tab,string][]=[["dashboard","ภาพรวม"],["reports","รายงานเดือนนี้"],["income","รายรับ"],["debt","หนี้สิน"],["assets","สินทรัพย์"],["investments","ลงทุน"],["expenses","ค่าใช้จ่าย"],["savings","เป้าหมาย"],["insurance","ประกัน"],["calendar","ปฏิทิน"]];
const clone=(x:any)=>JSON.parse(JSON.stringify(x)); const uid=()=>typeof crypto!=="undefined"&&crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`;
function loadLocal():FinanceState{if(typeof window==="undefined")return emptyState;try{const raw=JSON.parse(localStorage.getItem(KEY)||localStorage.getItem("finflow-state-v3")||"null");return {...emptyState,...raw,closedMonths:raw?.closedMonths||[]}}catch{return emptyState}}
function fmtDate(d:string){return new Intl.DateTimeFormat("th-TH",{day:"numeric",month:"short",year:"numeric"}).format(new Date(`${d}T00:00:00`))}
function localDateKey(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
type PaymentDisplayStatus="pending"|"paid"|"paid_more"|"paid_less"|"overdue";
function paymentDisplayStatus(p:Payment,today=localDateKey()):PaymentDisplayStatus{if(p.status==="paid"){const actual=Number(p.actualAmount??p.plannedAmount);if(actual>p.plannedAmount)return "paid_more";if(actual<p.plannedAmount)return "paid_less";return "paid";}return p.dueDate<=today?"overdue":"pending"}
function monthTitle(m:string){return new Intl.DateTimeFormat("th-TH",{month:"long",year:"numeric"}).format(new Date(`${m}-01T00:00:00`))}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}){return <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/30 p-0 backdrop-blur-sm sm:items-center sm:p-4"><div className="max-h-[94vh] w-full max-w-lg overflow-y-auto rounded-t-3xl bg-paper p-5 shadow-2xl sm:rounded-3xl sm:p-6"><div className="mb-5 flex items-center justify-between"><h2 className="text-xl font-semibold">{title}</h2><button onClick={onClose} className="rounded-xl p-2 hover:bg-[#F1E8DC]"><X size={19}/></button></div>{children}</div></div>}
function Field({label,value,onChange,type="text",placeholder="",required=false}:{label:string;value:any;onChange:(v:string)=>void;type?:string;placeholder?:string;required?:boolean}){return <label className="block"><span className="text-sm text-muted">{label}{required?" *":""}</span><input className="input mt-2" type={type} value={value??""} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></label>}
function Select({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:[string,string][]}){return <label className="block"><span className="text-sm text-muted">{label}</span><select className="input mt-2" value={value} onChange={e=>onChange(e.target.value)}>{options.map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label>}
function MonthNav({month,onMonth,closed}:{month:string;onMonth:(d:number)=>void;closed?:boolean}){return <div className="mb-4 flex items-center justify-between rounded-2xl border border-[#E9E0D3] bg-[#FBF7EF] px-3 py-2"><button className="rounded-xl p-2" onClick={()=>onMonth(-1)}><ChevronLeft/></button><div className="text-center"><p className="text-xs text-muted">เดือนที่กำลังดู</p><b>{monthTitle(month)}</b>{closed&&<p className="text-xs text-sage">🔒 ปิดเดือนแล้ว</p>}</div><button className="rounded-xl p-2" onClick={()=>onMonth(1)}><ChevronRight/></button></div>}
function Empty({text="ยังไม่มีข้อมูล"}){return <div className="rounded-2xl border border-dashed border-[#D8CCBC] p-6 text-center text-sm text-muted">{text}</div>}
function Actions({onEdit,onDelete,disabled=false,canEdit=true}:{onEdit:()=>void;onDelete:()=>void;disabled?:boolean;canEdit?:boolean}){
  if(!canEdit)return null;
  return <div className="flex gap-1">
    <button disabled={disabled} className="btn-soft !rounded-xl !px-2.5 !py-1.5 text-xs disabled:opacity-40" onClick={onEdit}>
      <Pencil size={13}/>
    </button>
    <button disabled={disabled} className="rounded-xl border border-[#E4D6C7] px-2.5 py-1.5 text-xs text-terracotta disabled:opacity-40" onClick={onDelete}>
      <Trash2 size={13}/>
    </button>
  </div>
}
function CrudCard({title,subtitle,onAdd,canEdit=true,children}:{title:string;subtitle?:string;onAdd:()=>void;canEdit?:boolean;children:ReactNode}){
  return <section className="card p-5 sm:p-6">
    <div className="mb-5 flex items-start justify-between gap-3">
      <div>
        <p className="text-xs uppercase tracking-wider text-muted">FinFlow</p>
        <h2 className="text-xl font-semibold">{title}</h2>
        {subtitle&&<p className="mt-1 text-sm text-muted">{subtitle}</p>}
      </div>
      {canEdit&&<button className="btn-soft flex items-center gap-1 !px-3 !py-2" onClick={onAdd}>
        <Plus size={16}/> เพิ่ม
      </button>}
    </div>
    {children}
  </section>
}
export default function Dashboard(){
 const { householdId, role } = useContext(HouseholdContext);
const canEdit = role === "OWNER" || role === "owner";
 const [state,setState]=useState<FinanceState>(emptyState),[ready,setReady]=useState(false),[syncing,setSyncing]=useState(false),[tab,setTab]=useState<Tab>("dashboard"),[month,setMonth]=useState(monthKey()),[modal,setModal]=useState<string|null>(null),[editing,setEditing]=useState<any>(null),[confirm,setConfirm]=useState<any>(null),[toast,setToast]=useState("");
 const cloudReady=!!supabase&&!!householdId;
 useEffect(()=>{
   let cancelled=false;
   async function loadState(){
     setReady(false);
     if(!cloudReady){ setState(emptyState); setReady(true); return; }
     setSyncing(true);
     try {
       const { data, error } = await supabase!.from("finance_states").select("id,state").eq("household_id",householdId).limit(1).maybeSingle();
       if(error) throw error;
       if(cancelled) return;
       if(data?.state){
         const cloud = { ...emptyState, ...data.state, closedMonths: data.state.closedMonths || [] } as FinanceState;
         setState(cloud);
         localStorage.setItem(KEY, JSON.stringify(cloud));
       } else {
         const local = loadLocal();
         setState(local);
         const { error: insertError } = await supabase!.from("finance_states").insert({ household_id: householdId, state: local });
         if(insertError) throw insertError;
       }
     } catch (e) {
       console.error("FinFlow cloud state load failed", e);
       const local = loadLocal();
       if(!cancelled) setState(local);
     } finally {
       if(!cancelled){ setSyncing(false); setReady(true); }
     }
   }
   void loadState();
   return ()=>{cancelled=true};
 },[householdId,cloudReady]);
 useEffect(()=>{
   if(!ready) return;
   localStorage.setItem(KEY,JSON.stringify(state));
   if(!cloudReady) return;
   const timer=setTimeout(async()=>{
     setSyncing(true);
     try {
       const { data, error } = await supabase!.from("finance_states").select("id").eq("household_id",householdId).limit(1).maybeSingle();
       if(error) throw error;
       if(data?.id){
         const { error: updateError } = await supabase!.from("finance_states").update({ state }).eq("id",data.id);
         if(updateError) throw updateError;
       } else {
         const { error: insertError } = await supabase!.from("finance_states").insert({ household_id: householdId, state });
         if(insertError) throw insertError;
       }
     } catch(e){ console.error("FinFlow cloud state save failed",e); }
     finally { setSyncing(false); }
   },350);
   return ()=>clearTimeout(timer);
 },[state,ready,householdId,cloudReady]);
 const closed=state.closedMonths.find(x=>x.month===month);const working=useMemo(()=>closed?{...state,payments:closed.payments,incomes:closed.incomes}:ensureMonthlyPayments(state,month),[state,month,closed]);const t=useMemo(()=>closed?closed.totals:totals(working,month),[working,month,closed]);const paymentHistory=useMemo(()=>{const byId=new Map<string,Payment>();[...state.payments,...working.payments].forEach(p=>byId.set(p.id,p));return [...byId.values()]},[state.payments,working.payments]);
 function flash(s:string){setToast(s);setTimeout(()=>setToast(""),2200)} function shift(d:number){const [y,m]=month.split("-").map(Number);setMonth(monthKey(new Date(y,m-1+d,1)))}
 function update(fn:(s:FinanceState)=>FinanceState){setState(s=>fn(clone(s)))}
 function addItem(kind:string,data:any){
  if(!canEdit){
    flash("สมาชิกสามารถดูข้อมูลได้อย่างเดียว");
    return;
  }

  update(s=>{
    (s as any)[kind].push({...data,id:uid()});
    return s;
  });

  setModal(null);
  flash("บันทึกข้อมูลแล้ว");
}
 function editItem(kind:string,data:any){
  if(!canEdit){flash("สมาชิกสามารถดูข้อมูลได้อย่างเดียว");return}
  if(closed){
function removeItem(kind:string,id:string,label:string){
  if(!canEdit){flash("สมาชิกสามารถดูข้อมูลได้อย่างเดียว");return}
  if(closed)
 function pay(p:Payment){if(closed)return;setEditing(p);setModal("payment")}
 function savePayment(p:Payment,actual:number,note:string){update(s=>{s.payments=s.payments.filter(x=>x.id!==p.id);s.payments.push({...p,actualAmount:actual,status:"paid",paidDate:p.paidDate||new Date().toISOString().slice(0,10),note});if(p.category==="debt"&&p.sourceId){const d=s.debts.find(x=>x.id===p.sourceId);if(d)d.currentBalance=Math.max(0,d.currentBalance-(actual||p.plannedAmount));}if(p.category==="asset_debt"&&p.sourceId){const a=s.assets.find(x=>x.id===p.sourceId);if(a)a.remainingDebt=Math.max(0,a.remainingDebt-(actual||p.plannedAmount));}if(p.category==="saving"&&p.sourceId){const g=s.savings.find(x=>x.id===p.sourceId);if(g)g.currentAmount=Math.min(g.targetAmount,g.currentAmount+(actual||p.plannedAmount));}if(p.category==="investment"&&p.sourceId){const i=s.investments.find(x=>x.id===p.sourceId);if(i)i.totalInvested+=(actual||p.plannedAmount);s.investmentEntries.push({id:uid(),investmentId:p.sourceId,month,amount:actual||p.plannedAmount});}return s});setModal(null);setEditing(null);flash("บันทึกการจ่ายแล้ว")}
 function closeMonth(){if(closed)return;const current=ensureMonthlyPayments(state,month);const summary=totals(current,month);const snap:MonthlySnapshot={month,incomes:clone(state.incomes.filter(x=>x.date.startsWith(month))),payments:clone(current.payments.filter(x=>x.dueDate.startsWith(month))),totals:{income:summary.income,allocated:summary.allocated,actual:summary.actual,cashFlow:summary.cashFlow,expense:summary.expense,debt:summary.debt,assetDebt:summary.assetDebt,insurance:summary.insurance,saving:summary.saving,investment:summary.investment,assets:summary.assets,liabilities:summary.liabilities,netWorth:summary.netWorth},closedAt:new Date().toISOString()};update(s=>{s.closedMonths=s.closedMonths.filter(x=>x.month!==month);s.closedMonths.push(snap);s.payments=current.payments;return s});setModal(null);flash(`ปิดเดือน${monthTitle(month)}แล้ว`)}
 function reset(){setState(emptyState);localStorage.removeItem(KEY);setConfirm(null);flash("เริ่มต้นใหม่แล้ว")}
 const openIncome=()=>{setEditing(null);setModal("income")};const editIncome=(x:Income)=>{setEditing(x);setModal("income")};
 return <main className="min-h-screen pb-24 md:pb-8"><div className="mx-auto max-w-7xl px-4 py-5 sm:px-6 lg:px-8">
  {syncing&&<div className="mb-3 text-right text-[11px] text-muted">กำลังซิงก์ข้อมูล...</div>}
  <header className="mb-5 flex items-center justify-between"><div><div className="flex items-center gap-2 text-sm text-muted"><span className="inline-flex h-8 w-8 items-center justify-center rounded-xl bg-[#E8DED0]"><CircleDollarSign size={17}/></span>FinFlow</div><h1 className="mt-1 text-2xl font-semibold">การเงินที่คุณควบคุมได้ 🌱</h1><p className="text-sm text-muted">วางแผน จ่ายจริง เห็นความคืบหน้า และค่อย ๆ ไปสู่อิสรภาพทางการเงิน</p></div><button className="btn-soft !p-3" onClick={()=>setModal("settings")}><Settings size={19}/></button></header>
  <div className="mb-5 flex gap-2 overflow-x-auto pb-1 md:flex-wrap">{tabs.map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`shrink-0 rounded-2xl px-3 py-2 text-sm ${tab===id?"bg-ink text-paper":"bg-[#FBF7EF] text-muted hover:bg-[#F1E8DC]"}`}>{label}</button>)}</div>
  {tab==="dashboard"&&<DashboardView state={working} rawState={state} t={t} month={month} closed={!!state.closedMonths.find(x=>x.month===month)} onTab={setTab} onCloseMonth={()=>{setModal("close")}}/>} 
  {tab==="income"&&<IncomeView items={working.incomes.filter(x=>x.date.startsWith(month))} month={month} closed={!!closed} onMonth={shift} onAdd={openIncome} onEdit={editIncome} onDelete={(x:Income)=>removeItem("incomes",x.id,x.name)}/>} 
  {tab==="debt"&&<DebtView items={state.debts} month={month} payments={paymentHistory} onAdd={()=>{setEditing(null);setModal("debt")}} onEdit={(x:any)=>{setEditing(x);setModal("debt")}} onDelete={(x:any)=>removeItem("debts",x.id,x.name)}/>} 
  {tab==="assets"&&<AssetView items={state.assets} month={month} payments={paymentHistory} onAdd={()=>{setEditing(null);setModal("asset")}} onEdit={(x:any)=>{setEditing(x);setModal("asset")}} onDelete={(x:any)=>removeItem("assets",x.id,x.name)}/>} 
  {tab==="investments"&&<InvestmentView items={state.investments} entries={state.investmentEntries} month={month} payments={paymentHistory} onAdd={()=>{setEditing(null);setModal("investment")}} onEdit={(x:any)=>{setEditing(x);setModal("investment")}} onDelete={(x:any)=>removeItem("investments",x.id,x.name)}/>} 
  {tab==="expenses"&&<SimpleList title="ค่าใช้จ่ายรายเดือน" subtitle="กำหนดแผนและวันจ่าย" items={state.expenses} paymentCategory="expense" payments={paymentHistory} onAdd={()=>{setEditing(null);setModal("expense")}} onEdit={(x:any)=>{setEditing(x);setModal("expense")}} onDelete={(x:any)=>removeItem("expenses",x.id,x.name)} render={(x:any)=><><b>{x.name}</b><p className="text-xs text-muted">แผน {money(x.plannedAmount)} · วันที่ {x.paymentDay}</p></>}/>} 
  {tab==="savings"&&<SavingView items={state.savings} month={month} payments={paymentHistory} onAdd={()=>{setEditing(null);setModal("saving")}} onEdit={(x:any)=>{setEditing(x);setModal("saving")}} onDelete={(x:any)=>removeItem("savings",x.id,x.name)}/>} 
  {tab==="insurance"&&<SimpleList title="ประกัน" subtitle="เบี้ยประกันจะถูกนำไปเป็นรายจ่ายของเดือน" items={state.insurance} onAdd={()=>{setEditing(null);setModal("insurance")}} onEdit={(x:any)=>{setEditing(x);setModal("insurance")}} onDelete={(x:any)=>removeItem("insurance",x.id,x.company)} render={(x:any)=><><b>{x.company}</b><p className="text-xs text-muted">เบี้ย {money(x.premiumAmount)} · วันที่ {x.premiumDay}</p></>}/>} 
  {tab==="calendar"&&<CalendarView payments={working.payments.filter(p=>p.dueDate.startsWith(month))} month={month} onMonth={shift} onPay={pay}/>} 
  {tab==="reports"&&<Reports state={working} month={month} t={t} onMonth={shift} closed={!!closed} onTab={setTab} onCloseMonth={()=>{setModal("close")}}/>} 
 </div>
 <div className="fixed inset-x-0 bottom-0 z-20 border-t border-[#E2D8CA] bg-paper/95 px-3 py-2 backdrop-blur md:hidden"><div className="mx-auto flex max-w-md items-center justify-around"><button onClick={()=>setTab("dashboard")} className="text-xs">🏠<br/>ภาพรวม</button><button onClick={()=>setTab("calendar")} className="text-xs">📅<br/>ปฏิทิน</button><button onClick={openIncome} className="flex h-12 w-12 items-center justify-center rounded-2xl bg-ink text-paper"><Plus/></button><button onClick={()=>setTab("reports")} className="text-xs">📊<br/>รายงานเดือนนี้</button><button onClick={()=>setModal("settings")} className="text-xs">⚙️<br/>ตั้งค่า</button></div></div>
 {modal==="income"&&<IncomeModal item={editing} defaultMonth={month} onClose={()=>setModal(null)} onSave={(x:any)=>editing?editItem("incomes",x):addItem("incomes",x)}/>} 
 {modal==="debt"&&<DebtModal item={editing} onClose={()=>setModal(null)} onSave={(x:any)=>editing?editItem("debts",x):addItem("debts",x)}/>} 
 {modal==="asset"&&<AssetModal item={editing} month={month} onClose={()=>setModal(null)} onSave={(x:any)=>editing?editItem("assets",x):addItem("assets",x)}/>} 
 {modal==="investment"&&<InvestmentModal item={editing} onClose={()=>setModal(null)} onSave={(x:any)=>editing?editItem("investments",x):addItem("investments",x)}/>} 
 {modal==="expense"&&<ExpenseModal item={editing} onClose={()=>setModal(null)} onSave={(x:any)=>editing?editItem("expenses",x):addItem("expenses",x)}/>} 
 {modal==="saving"&&<SavingModal item={editing} month={month} onClose={()=>setModal(null)} onSave={(x:any)=>editing?editItem("savings",x):addItem("savings",x)}/>} 
 {modal==="insurance"&&<InsuranceModal item={editing} onClose={()=>setModal(null)} onSave={(x:any)=>editing?editItem("insurance",x):addItem("insurance",x)}/>} 
 {modal==="payment"&&<PaymentModal p={editing} onClose={()=>setModal(null)} onSave={savePayment}/>} 
 {modal==="close"&&<CloseMonthModal month={month} t={t} onCancel={()=>setModal(null)} onConfirm={closeMonth}/>} 
 {modal==="settings"&&<Modal title="ตั้งค่า" onClose={()=>setModal(null)}><div className="space-y-3"><div className="rounded-2xl bg-[#FBF7EF] p-4 text-sm">ข้อมูลเก็บใน browser เครื่องนี้ก่อน และแต่ละเดือนที่ปิดจะถูกเก็บเป็น snapshot แยกจากเดือนอื่น</div><button onClick={()=>{setModal(null);setConfirm({title:"เริ่มต้นใหม่",description:<p>ล้างข้อมูลทั้งหมด? <b>ย้อนกลับไม่ได้</b></p>,action:reset})}} className="flex w-full items-center gap-3 rounded-2xl border border-[#E8CFC4] bg-[#FFF8F5] p-4 text-left text-terracotta"><RotateCcw/><span><b>เริ่มต้นใหม่</b><span className="block text-xs">ล้างข้อมูลทั้งหมด</span></span></button></div></Modal>}
 {confirm&&<ConfirmModal title={confirm.title} description={confirm.description} onCancel={()=>setConfirm(null)} onConfirm={confirm.action}/>} {toast&&<div className="fixed right-4 top-4 z-[60] rounded-2xl bg-ink px-4 py-3 text-sm text-paper shadow-xl">{toast}</div>}
 </main>
}
function ConfirmModal({title,description,onCancel,onConfirm}:{title:string;description:ReactNode;onCancel:()=>void;onConfirm:()=>void}){return <Modal title={title} onClose={onCancel}><div className="rounded-2xl bg-[#FFF8F5] p-4 text-sm"><div className="flex gap-3"><AlertTriangle className="shrink-0 text-terracotta"/>{description}</div></div><div className="mt-5 flex gap-2"><button className="btn-soft flex-1" onClick={onCancel}>ยกเลิก</button><button className="rounded-2xl bg-terracotta px-4 py-3 text-sm font-medium text-white" onClick={onConfirm}>ยืนยัน</button></div></Modal>}
function DashboardView({state,rawState,t,month,closed,onTab,onCloseMonth}:{state:FinanceState;rawState:FinanceState;t:any;month:string;closed:boolean;onTab:(t:Tab)=>void;onCloseMonth:()=>void}){
 const currentMonth=monthKey();
 const currentWorking=useMemo(()=>ensureMonthlyPayments(rawState,currentMonth),[rawState,currentMonth]);
 const currentTotals=useMemo(()=>totals(currentWorking,currentMonth),[currentWorking,currentMonth]);
 const currentNetWorth=currentTotals.netWorth;
 const netClass=currentNetWorth>=0?"text-[#5F7F63]":"text-[#A35F57]";
 const debtOriginal=rawState.debts.reduce((s,d)=>s+Math.max(0,d.originalPrincipal),0)+rawState.assets.reduce((s,a)=>s+(a.financed?Math.max(0,a.originalDebt??a.remainingDebt):0),0);
 const debtCurrent=rawState.debts.reduce((s,d)=>s+Math.max(0,d.currentBalance),0)+rawState.assets.reduce((s,a)=>s+(a.financed?Math.max(0,a.remainingDebt):0),0);
 const debtReduced=Math.max(0,debtOriginal-debtCurrent);
 const trend=useMemo(()=>{
   const [y,m]=currentMonth.split("-").map(Number);
   const months=Array.from({length:6},(_,i)=>monthKey(new Date(y,m-1-(5-i),1)));
   return months.map(mk=>{
     const snap=rawState.closedMonths.find(x=>x.month===mk);
     if(snap)return {month:mk,label:new Intl.DateTimeFormat("th-TH",{month:"short"}).format(new Date(`${mk}-01T00:00:00`)),income:snap.totals.income,expense:snap.totals.expense+snap.totals.debt+snap.totals.assetDebt+snap.totals.saving+snap.totals.insurance,investment:snap.totals.investment};
     if(mk===currentMonth)return {month:mk,label:new Intl.DateTimeFormat("th-TH",{month:"short"}).format(new Date(`${mk}-01T00:00:00`)),income:currentTotals.income,expense:currentTotals.expense+currentTotals.debt+currentTotals.assetDebt+currentTotals.saving+currentTotals.insurance,investment:currentTotals.investment};
     return {month:mk,label:new Intl.DateTimeFormat("th-TH",{month:"short"}).format(new Date(`${mk}-01T00:00:00`)),income:0,expense:0,investment:0};
   });
 },[rawState.closedMonths,currentMonth,currentTotals]);
 const trendMax=Math.max(1,...trend.flatMap(x=>[x.income,x.expense,x.investment]));
 const financedAssets=rawState.assets.filter(a=>a.financed);
 const debtFreedomOriginal=debtOriginal;
 const debtFreedomCurrent=debtCurrent;
 const debtFreedomPercent=debtFreedomOriginal>0?progress(debtFreedomOriginal,debtFreedomCurrent):0;
 const debtPayments=currentWorking.payments.filter(p=>p.category==="debt"||p.category==="asset_debt");
 const debtOverdue=debtPayments.some(p=>paymentDisplayStatus(p,currentMonth===month?localDateKey():`${currentMonth}-99`)==="overdue");
 const debtPaidLess=debtPayments.some(p=>paymentDisplayStatus(p)==="paid_less");
 const debtFreedomMessage=debtOverdue?"⚠️ มีรายการหนี้เกินกำหนด ควรจัดการก่อน":debtPaidLess?"⚠️ เดือนนี้มีรายการที่จ่ายต่ำกว่าแผน":debtFreedomCurrent<=0?"🎉 ปลดหนี้ทั้งหมดได้แล้ว":debtFreedomOriginal>0?`🌱 คุณปลดหนี้ไปแล้ว ${debtFreedomPercent.toFixed(0)}% เหลือ ${money(debtFreedomCurrent)}`:"เริ่มต้นเส้นทางปลดหนี้ได้เลย";
 return <>
  <section className="grid gap-4 lg:grid-cols-3">
   <Metric title="ความมั่งคั่งสุทธิ" value={money(currentNetWorth)} className={netClass} hint={`ทรัพย์สิน ${money(currentTotals.assets)} · หนี้ ${money(currentTotals.liabilities)}`} icon={<Landmark/>}/>
   <Metric title="หนี้ลดไปแล้ว" value={money(debtReduced)} hint={`จากยอดหนี้เริ่มต้น ${money(debtOriginal)} · เหลือ ${money(debtCurrent)}`} icon={<TrendingUp/>}/>
   <section className="card p-5 lg:row-span-2"><div className="flex items-center justify-between"><div><p className="text-xs uppercase tracking-wider text-muted">Debt freedom</p><h2 className="text-xl font-semibold">เส้นทางปลดหนี้</h2></div><TrendingUp size={20}/></div><div className="mt-3 rounded-2xl bg-[#FBF7EF] p-4"><p className="text-sm font-medium">{debtFreedomMessage}</p><div className="mt-3 grid grid-cols-3 gap-2 text-xs"><div><p className="text-muted">ภาระเริ่มต้น</p><p className="mt-1 font-semibold">{money(debtFreedomOriginal)}</p></div><div><p className="text-muted">ลดไปแล้ว</p><p className="mt-1 font-semibold">{money(Math.max(0,debtFreedomOriginal-debtFreedomCurrent))}</p></div><div><p className="text-muted">เหลือ</p><p className="mt-1 font-semibold">{money(debtFreedomCurrent)}</p></div></div><div className="mt-3 h-2 rounded-full bg-[#E8DED0]"><div className="h-full rounded-full bg-earth" style={{width:`${debtFreedomPercent}%`}}/></div><p className="mt-2 text-xs text-muted">รวม หนี้สิน + สินทรัพย์ที่ยังผ่อน · ปลดแล้ว {debtFreedomPercent.toFixed(0)}%</p></div><div className="mt-4 space-y-4">{rawState.debts.length?rawState.debts.map(d=><DebtProgress key={d.id} d={d} month={currentMonth}/>):<Empty text="ยังไม่มีหนี้"/>}{financedAssets.length>0&&<div className="border-t border-[#EAE1D5] pt-4 space-y-4">{financedAssets.map(a=><AssetDebtProgress key={a.id} a={a} month={currentMonth}/>)}</div>}</div></section>
   <section className="card p-5 lg:col-span-2"><div className="flex items-center justify-between"><div><p className="text-xs uppercase tracking-wider text-muted">6 เดือนล่าสุด</p><h2 className="text-xl font-semibold">แนวโน้มรายรับและการใช้เงิน</h2><p className="text-sm text-muted">เปรียบเทียบรายรับ · รายจ่ายรวม · ลงทุน โดยเดือนปัจจุบันอยู่ด้านขวาสุด</p></div></div><div className="mt-5 flex h-56 items-end gap-2 border-b border-[#EAE1D5] px-1">{trend.map(x=><div key={x.month} className="flex min-w-0 flex-1 flex-col items-center justify-end gap-2"><div className="flex h-44 w-full max-w-16 items-end justify-center gap-1"><div title={`รายรับ ${money(x.income)}`} className="w-1/3 rounded-t-md bg-sage" style={{height:`${Math.max(x.income?3:0,x.income/trendMax*100)}%`}}/><div title={`รายจ่าย ${money(x.expense)}`} className="w-1/3 rounded-t-md bg-earth" style={{height:`${Math.max(x.expense?3:0,x.expense/trendMax*100)}%`}}/><div title={`ลงทุน ${money(x.investment)}`} className="w-1/3 rounded-t-md bg-[#879AA0]" style={{height:`${Math.max(x.investment?3:0,x.investment/trendMax*100)}%`}}/></div><span className={`text-xs ${x.month===currentMonth?"font-semibold text-ink":"text-muted"}`}>{x.label}</span></div>)}</div><div className="mt-4 flex flex-wrap gap-x-5 gap-y-2 text-xs text-muted"><span className="inline-flex items-center gap-2"><i className="h-2.5 w-2.5 rounded-sm bg-sage"/>รายรับ</span><span className="inline-flex items-center gap-2"><i className="h-2.5 w-2.5 rounded-sm bg-earth"/>รายจ่าย (หนี้ + สินทรัพย์ + รายจ่าย + เป้าหมาย)</span><span className="inline-flex items-center gap-2"><i className="h-2.5 w-2.5 rounded-sm bg-[#879AA0]"/>ลงทุน</span></div></section>
  </section>
 </>
}
function Metric({title,value,hint,icon,className=""}:{title:string;value:string;hint:string;icon:ReactNode;className?:string}){return <div className="card p-5"><div className="flex justify-between"><p className="text-sm text-muted">{title}</p><span className="rounded-xl bg-[#F0E7DA] p-2">{icon}</span></div><p className={`mt-4 text-2xl font-semibold ${className}`}>{value}</p><p className="mt-1 text-xs text-muted">{hint}</p></div>}
function DebtProgress({d,month}:{d:Debt;month:string}){const p=progress(d.originalPrincipal,d.currentBalance);const payment=d.monthlyPayment>0?d.monthlyPayment:monthlyDebtPayment(d.currentBalance,d.annualInterestRate);const months=payoffMonths(d.currentBalance,d.annualInterestRate,payment);const date=payoffDate(month,d.currentBalance,d.annualInterestRate,payment);return <div><div className="flex justify-between text-sm"><b>{d.name}</b><span>{p.toFixed(0)}%</span></div><div className="mt-2 h-2 rounded-full bg-[#E8DED0]"><div className="h-full rounded-full bg-earth" style={{width:`${p}%`}}/></div><p className="mt-1 text-xs text-muted">ลดแล้ว {money(d.originalPrincipal-d.currentBalance)} · เหลือ {money(d.currentBalance)} · {Number.isFinite(months)?`${months} เดือน`:"ยังคำนวณไม่ได้"}{date&&<span className="text-[#A35F57]"> · คาดว่า {monthTitle(date)} ปลดหนี้</span>}</p></div>}
function AssetDebtProgress({a,month}:{a:Asset;month:string}){const start=a.originalDebt||a.remainingDebt;const p=progress(start,a.remainingDebt);const payment=assetMonthlyPlan(a,month);const months=payoffMonths(a.remainingDebt,a.annualInterestRate,payment);const date=payoffDate(month,a.remainingDebt,a.annualInterestRate,payment);return <div><div className="flex justify-between text-sm"><b>{a.name}</b><span>{p.toFixed(0)}%</span></div><div className="mt-2 h-2 rounded-full bg-[#E8DED0]"><div className="h-full rounded-full bg-earth" style={{width:`${p}%`}}/></div><p className="mt-1 text-xs text-muted">ลดแล้ว {money(Math.max(0,start-a.remainingDebt))} · เหลือ {money(a.remainingDebt)} · {Number.isFinite(months)?`${months} เดือน`:"ยังคำนวณไม่ได้"}{date&&<span className="text-[#A35F57]"> · คาดว่า {monthTitle(date)} ปลดหนี้</span>}</p></div>}
function IncomeView({items,month,closed,onMonth,onAdd,onEdit,onDelete}:any){const total=items.reduce((s:any,x:Income)=>s+x.amount,0);return <section className="card p-5 sm:p-6"><MonthNav month={month} onMonth={onMonth} closed={closed}/><div className="mb-5 flex items-center justify-between"><div><h2 className="text-xl font-semibold">รายรับเดือนนี้</h2><p className="text-sm text-muted">บันทึกเฉพาะรายได้ที่เกิดขึ้นจริงของเดือนนี้ด้วยตัวเอง</p></div>{!closed&&<button className="btn-soft flex items-center gap-1" onClick={onAdd}><Plus size={16}/> เพิ่มรายรับ</button>}</div><div className="mb-4 rounded-2xl bg-[#FBF7EF] p-4"><p className="text-xs text-muted">รายรับรวม</p><p className="mt-1 text-2xl font-semibold">{money(total)}</p></div>{items.length?<div className="space-y-3">{items.map((x:Income)=><div className="flex items-center gap-3 rounded-2xl border border-[#EAE1D5] p-4" key={x.id}><Wallet/><div className="flex-1"><b>{x.name}</b><p className="text-xs text-muted">{fmtDate(x.date)}</p></div><b>{money(x.amount)}</b><Actions disabled={closed} onEdit={()=>onEdit(x)} onDelete={()=>onDelete(x)}/></div>)}</div>:<Empty text="เดือนนี้ยังไม่มีรายรับที่บันทึก"/>}</section>}
function PaymentHistory({payments,sourceId,category}:{payments:Payment[];sourceId:string;category:Payment["category"]}){const [open,setOpen]=useState(false);const records=payments.filter(p=>p.sourceId===sourceId&&p.category===category).sort((a,b)=>((b.paidDate||b.dueDate).localeCompare(a.paidDate||a.dueDate)));const statusText=(p:Payment)=>{const s=paymentDisplayStatus(p);return s==="paid"?"จ่ายแล้ว":s==="paid_more"?"จ่ายมากกว่าแผน":s==="paid_less"?"จ่ายน้อยกว่าแผน":s==="overdue"?"เกินกำหนด":"รอจ่าย"};return <div className="mt-4 border-t border-[#EAE1D5] pt-3"><button type="button" className="flex w-full items-center justify-between rounded-xl bg-[#FBF7EF] px-3 py-2 text-sm" onClick={()=>setOpen(v=>!v)}><span className="font-medium">ประวัติการจ่าย</span><span className="text-xs text-muted">{records.length} รายการ · {open?"ซ่อน":"ดูประวัติ"}</span></button>{open&&<div className="mt-2 space-y-2">{records.length?records.map(p=>{const displayStatus=paymentDisplayStatus(p);const paidDate=p.paidDate||((p.status==="paid")?p.dueDate:"");const onTime=paidDate&&paidDate<=p.dueDate;const statusColor=displayStatus==="paid"?"bg-[#E8F0E8] text-[#5F7F63]":displayStatus==="paid_more"?"bg-[#E8F0E8] text-[#5F7F63]":displayStatus==="paid_less"?"bg-[#FFF0E8] text-[#A35F57]":displayStatus==="overdue"?"bg-[#FFF0E8] text-[#A35F57]":"bg-[#F1E8DC] text-muted";return <div key={p.id} className="rounded-xl border border-[#EAE1D5] bg-[#FFFCF7] p-3 text-sm"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="font-medium">ยอดจ่าย {money(p.actualAmount??p.plannedAmount)} · แผน {money(p.plannedAmount)}</p><p className="mt-1 text-xs text-muted">กำหนดจ่าย {fmtDate(p.dueDate)} · {displayStatus.startsWith("paid")?`วันที่จ่าย ${fmtDate(paidDate)}`:"ยังไม่ได้จ่าย"}</p>{p.note&&<p className="mt-1 text-xs text-muted">หมายเหตุ: {p.note}</p>}</div><span className={`shrink-0 rounded-full px-2 py-1 text-xs ${statusColor}`}>{statusText(p)}</span></div>{displayStatus.startsWith("paid")&&<p className="mt-2 text-xs text-muted">{onTime?"จ่ายตามกำหนด":"จ่ายหลังกำหนด"}</p>}</div>}) : <Empty text="ยังไม่มีประวัติการจ่าย"/>}</div>}</div>}
function DebtView({items,month,payments,onAdd,onEdit,onDelete}:any){return <CrudCard title="หนี้สิน" subtitle="ติดตามยอดคงเหลือและเส้นทางปลดหนี้" onAdd={onAdd}>{items.length?<div className="space-y-3">{items.map((d:Debt)=><div className="rounded-2xl border border-[#EAE1D5] p-4" key={d.id}><div className="flex justify-between"><div><b>{d.name}</b><p className="text-xs text-muted">เริ่ม {money(d.originalPrincipal)} · เหลือ {money(d.currentBalance)}</p></div><Actions onEdit={()=>onEdit(d)} onDelete={()=>onDelete(d)}/></div><DebtProgress d={d} month={month}/><PaymentHistory payments={payments} sourceId={d.id} category="debt"/></div>)}</div>:<Empty text="ยังไม่มีหนี้"/>}</CrudCard>}
function AssetView({items,month,payments,onAdd,onEdit,onDelete}:any){return <CrudCard title="สินทรัพย์" subtitle="ติดตามมูลค่าทรัพย์สินและภาระผ่อนพร้อมยอดกันเงินต่อเดือน" onAdd={onAdd}>{items.length?<div className="space-y-3">{items.map((a:Asset)=><div key={a.id} className="rounded-2xl border border-[#EAE1D5] p-4"><div className="flex gap-3"><Home/><div className="flex-1"><div className="flex justify-between"><div><b>{a.name}</b><p className="text-xs text-muted">{a.type} · มูลค่า {money(a.value)}</p></div><Actions onEdit={()=>onEdit(a)} onDelete={()=>onDelete(a)}/></div>{a.financed&&<><div className="mt-3 flex justify-between text-sm"><span>ความคืบหน้าการผ่อน</span><span>{progress(a.originalDebt||a.remainingDebt,a.remainingDebt).toFixed(0)}%</span></div><div className="mt-2 h-2 rounded-full bg-[#E8DED0]"><div className="h-full rounded-full bg-earth" style={{width:`${progress(a.originalDebt||a.remainingDebt,a.remainingDebt)}%`}}/></div><div className="mt-2 grid gap-1 text-xs text-muted sm:grid-cols-3"><span>เหลือ {money(a.remainingDebt)}</span><span>กัน/เดือน {money(assetMonthlyPlan(a,month))}</span><span>{a.targetDate?`เหลือ ${monthsUntil(a.targetDate,month)} เดือน`:"ไม่มีวันเป้าหมาย"}</span></div><PaymentHistory payments={payments} sourceId={a.id} category="asset_debt"/></>}</div></div></div>)}</div>:<Empty/>}</CrudCard>}
function InvestmentView({items,entries,month,payments,onAdd,onEdit,onDelete}:any){return <CrudCard title="การลงทุน" subtitle="บันทึกการลงทุนจริงรายเดือน" onAdd={onAdd}>{items.length?<div className="space-y-3">{items.map((i:Investment)=><div key={i.id} className="flex gap-3 rounded-2xl border border-[#EAE1D5] p-4"><TrendingUp/><div className="flex-1"><div className="flex justify-between"><b>{i.name}</b><Actions onEdit={()=>onEdit(i)} onDelete={()=>onDelete(i)}/></div><p className="text-xs text-muted">วันที่ {i.investmentDay} · เป้าต่อเดือน {money(i.monthlyTarget)}</p><p className="mt-1 text-sm">สะสม {money(i.totalInvested)} · เดือนนี้ {money(entries.filter((e:any)=>e.investmentId===i.id&&e.month===month).reduce((s:number,e:any)=>s+e.amount,0))}</p><PaymentHistory payments={payments} sourceId={i.id} category="investment"/></div></div>)}</div>:<Empty/>}</CrudCard>}
function SimpleList({title,subtitle,items,payments,paymentCategory,onAdd,onEdit,onDelete,render}:any){return <CrudCard title={title} subtitle={subtitle} onAdd={onAdd}>{items.length?<div className="space-y-3">{items.map((x:any)=><div className="rounded-2xl border border-[#EAE1D5] p-4" key={x.id}><div className="flex items-center gap-3"><div className="flex-1">{render(x)}</div><Actions onEdit={()=>onEdit(x)} onDelete={()=>onDelete(x)}/></div>{paymentCategory&&<PaymentHistory payments={payments} sourceId={x.id} category={paymentCategory}/>}</div>)}</div>:<Empty/>}</CrudCard>}
function SavingView({items,month,payments,onAdd,onEdit,onDelete}:any){return <CrudCard title="เป้าหมาย" subtitle="ถ้ามีวันเป้าหมาย ระบบคำนวณยอดที่ต้องกันในเดือนนั้นให้อัตโนมัติ" onAdd={onAdd}>{items.length?<div className="space-y-3">{items.map((g:SavingGoal)=><div className="rounded-2xl border border-[#EAE1D5] p-4" key={g.id}><div className="flex justify-between"><div><b>{g.name}</b><p className="text-xs text-muted">{money(g.currentAmount)} / {money(g.targetAmount)}</p></div><Actions onEdit={()=>onEdit(g)} onDelete={()=>onDelete(g)}/></div><div className="mt-3 h-2 rounded-full bg-[#E8DED0]"><div className="h-full rounded-full bg-sage" style={{width:`${goalProgress(g.currentAmount,g.targetAmount)}%`}}/></div><p className="mt-2 text-xs text-muted">เดือนนี้ต้องกัน {money(g.monthlyAmount>0?g.monthlyAmount:(g.targetDate?Math.ceil(Math.max(0,g.targetAmount-g.currentAmount)/monthsUntil(g.targetDate,month)):Math.max(0,g.targetAmount-g.currentAmount)))}</p><PaymentHistory payments={payments} sourceId={g.id} category="saving"/></div>)}</div>:<Empty/>}</CrudCard>}
function CalendarView({payments,month,onMonth,onPay}:any){const total=payments.reduce((s:number,p:Payment)=>s+p.plannedAmount,0);return <section className="card p-5 sm:p-6"><MonthNav month={month} onMonth={onMonth}/><div className="mb-5 rounded-2xl bg-[#FBF7EF] p-4"><p className="text-xs text-muted">รวมต้องจ่ายตามแผนเดือนนี้</p><p className="mt-1 text-2xl font-semibold">{money(total)}</p></div><div className="space-y-2">{payments.length?payments.sort((a:Payment,b:Payment)=>a.dueDate.localeCompare(b.dueDate)).map((p:Payment)=><PaymentRow key={p.id} p={p} onPay={onPay}/>):<Empty text="ไม่มีรายการกำหนดจ่ายเดือนนี้"/>}</div></section>}
function PaymentRow({p,onPay}:{p:Payment;onPay:(p:Payment)=>void}){const displayStatus=paymentDisplayStatus(p);const paid=displayStatus.startsWith("paid");const statusText=displayStatus==="paid"?"จ่ายแล้ว":displayStatus==="paid_more"?"จ่ายมากกว่าแผน":displayStatus==="paid_less"?"จ่ายน้อยกว่าแผน":displayStatus==="overdue"?"เกินกำหนด":"รอจ่าย";return <div className="flex items-center gap-3 rounded-2xl border border-[#EAE1D5] bg-[#FFFCF7] p-3"><div className="min-w-0 flex-1"><p className={`font-medium ${paid?"line-through text-muted":""}`}>{p.title}</p><p className="text-xs text-muted">{fmtDate(p.dueDate)} · แผน {money(p.plannedAmount)}{p.note?` · ${p.note}`:""}</p><span className={`mt-1 inline-flex rounded-full px-2 py-1 text-[11px] ${displayStatus==="paid"?"bg-[#E8F0E8] text-[#5F7F63]":displayStatus==="paid_more"?"bg-[#E8F0E8] text-[#5F7F63]":displayStatus==="paid_less"||displayStatus==="overdue"?"bg-[#FFF0E8] text-[#A35F57]":"bg-[#F1E8DC] text-muted"}`}>{statusText}</span></div><div className="text-right"><p className="font-medium">{money(p.actualAmount??p.plannedAmount)}</p><button className={paid?"text-xs text-sage":"btn-primary !rounded-xl !px-3 !py-2 !text-xs"} onClick={()=>onPay(p)}>{paid?<><Check size={14} className="inline"/> แก้ไขยอด</>:"จ่ายแล้ว"}</button></div></div>}
function Mini({title,value}:{title:string;value:number}){return <div className="rounded-2xl bg-[#FBF7EF] p-4"><p className="text-xs text-muted">{title}</p><p className="mt-1 text-lg font-semibold">{money(value)}</p></div>}
function Reports({state,month,t,onMonth,closed,onTab,onCloseMonth}:any){
 const categories=[['หนี้',t.debt],['สินทรัพย์',t.assetDebt],['รายจ่าย',t.expense+t.insurance],['เป้าหมาย',t.saving],['ลงทุน',t.investment]] as [string,number][];
 const allocatedTotal=categories.reduce((s,x)=>s+x[1],0);
 const donutColors=["#A97861","#8A7153","#7E8F73","#B6A079","#879AA0"];
 const donutTotal=allocatedTotal;
 const donutBackground=donutTotal?`conic-gradient(${categories.map(([,v],i)=>`${donutColors[i]} ${categories.slice(0,i).reduce((s,x)=>s+x[1],0)/donutTotal*360}deg ${categories.slice(0,i+1).reduce((s,x)=>s+x[1],0)/donutTotal*360}deg`).join(",")})` : "#E8DED0";
 return <div className="space-y-4">
  <MonthNav month={month} onMonth={onMonth} closed={closed}/>
  <section className="card p-5">
   <p className="text-xs uppercase tracking-wider text-muted">Monthly report</p>
   <h2 className="text-xl font-semibold">รายงานเดือนนี้ · {monthTitle(month)}</h2>
   <div className="mt-5 grid gap-3 sm:grid-cols-3"><Mini title="รายรับ" value={t.income}/><Mini title="ยอดจัดสรร" value={t.allocated}/><Mini title="จ่ายจริง" value={t.actual}/></div>
  </section>
  <section className="grid gap-4 lg:grid-cols-2">
   <section className="card p-5">
    <div className="flex items-center justify-between"><div><p className="text-xs uppercase tracking-wider text-muted">Monthly payments</p><h2 className="text-xl font-semibold">ต้องจ่ายเดือนนี้</h2></div><button className="btn-soft" onClick={()=>onTab("calendar")}>ดูทั้งหมด</button></div>
    <p className="mt-5 text-3xl font-semibold">{money(t.allocated)}</p>
   </section>
   <section className="card p-5">
    <div><p className="text-xs uppercase tracking-wider text-muted">Monthly allocation</p><h2 className="text-xl font-semibold">เงินเดือนเดือนนี้ไปทางไหน</h2></div>
    <div className="mt-5 flex flex-col items-center gap-5 sm:flex-row">
     <div className="donut" style={{background:donutBackground}}><div className="donut-hole"><b>{money(allocatedTotal)}</b><span>จ่ายจริง</span></div></div>
     <div className="w-full space-y-2 text-sm">{categories.map(([label,v],i)=>{const pct=donutTotal?Math.round(v/donutTotal*100):0;return <div className="flex items-center justify-between gap-3" key={label}><span className="flex items-center gap-2"><i className="h-2.5 w-2.5 rounded-sm" style={{background:donutColors[i]}}/>{label}</span><span><b>{pct}%</b> · {money(v)}</span></div>})}</div>
    </div>
   </section>
  </section>
  <section className="card p-5"><div className="flex items-center justify-between gap-4"><div><p className="text-xs uppercase tracking-wider text-muted">Month closing</p><h2 className="text-xl font-semibold">{closed?"🔒 เดือนนี้ปิดแล้ว":"บันทึกและปิดเดือน"}</h2></div>{!closed&&<button className="btn-primary" onClick={onCloseMonth}>บันทึกและปิดเดือน</button>}</div>{closed?<p className="mt-2 text-sm text-muted">ข้อมูลเดือน {monthTitle(month)} ถูกเก็บเป็นประวัติของเดือนนี้ และไม่เชื่อมแก้กับเดือนอื่น</p>:<p className="mt-2 text-sm text-muted">เมื่อพร้อมแล้วให้ยืนยันเพื่อ freeze รายได้ รายจ่าย และยอดจ่ายจริงของเดือนนี้</p>}</section>
 </div>}
function CloseMonthModal({month,t,onCancel,onConfirm}:any){return <Modal title={`สรุปก่อนปิดเดือน ${monthTitle(month)}`} onClose={onCancel}><div className="space-y-2 rounded-2xl bg-[#FBF7EF] p-4 text-sm"><p>รายรับจริง <b className="float-right">{money(t.income)}</b></p><p>ยอดจัดสรร <b className="float-right">{money(t.allocated)}</b></p><p>จ่ายจริง <b className="float-right">{money(t.actual)}</b></p><p>กระแสเงินสด <b className="float-right">{money(t.cashFlow)}</b></p></div><div className="mt-4 rounded-2xl bg-[#FFF8F5] p-4 text-sm"><b>เมื่อปิดเดือนแล้ว</b><p className="mt-1 text-muted">ข้อมูลของ {monthTitle(month)} จะถูกบันทึกเป็น snapshot ของเดือนนั้น และไม่สามารถแก้ย้อนหลังได้</p></div><div className="mt-5 flex gap-2"><button className="btn-soft flex-1" onClick={onCancel}>กลับไปตรวจสอบ</button><button className="btn-primary flex-1" onClick={onConfirm}>🔒 ยืนยันปิดเดือน</button></div></Modal>}
function IncomeModal({item,defaultMonth,onClose,onSave}:any){const [f,setF]=useState<Income>(item||{id:uid(),name:"",amount:0,date:`${defaultMonth}-25`});return <Modal title={item?"แก้ไขรายรับ":"เพิ่มรายรับ"} onClose={onClose}><div className="space-y-3"><Field label="ชื่อรายได้" required value={f.name} onChange={v=>setF({...f,name:v})}/><Field label="ยอดรายได้จริง" required type="number" value={f.amount} onChange={v=>setF({...f,amount:Number(v)})}/><Field label="วันที่รับรายได้" required type="date" value={f.date} onChange={v=>setF({...f,date:v})}/></div><button className="btn-primary mt-5 w-full" disabled={!f.name||f.amount<=0} onClick={()=>onSave(f)}>บันทึก</button></Modal>}
function DebtModal({item,onClose,onSave}:any){const [f,setF]=useState<Debt>(item||{id:uid(),name:"",originalPrincipal:0,currentBalance:0,annualInterestRate:0,monthlyPayment:0,paymentDay:1,status:"active"});const auto=f.monthlyPayment<=0;const min=auto?monthlyDebtPayment(f.currentBalance,f.annualInterestRate):f.monthlyPayment;return <Modal title={item?"แก้ไขหนี้":"เพิ่มหนี้"} onClose={onClose}><div className="space-y-3"><Field label="ชื่อหนี้" required value={f.name} onChange={v=>setF({...f,name:v})}/><Field label="ยอดหนี้เริ่มต้น" required type="number" value={f.originalPrincipal} onChange={v=>setF({...f,originalPrincipal:Number(v)})}/><Field label="ยอดหนี้คงเหลือ" required type="number" value={f.currentBalance} onChange={v=>setF({...f,currentBalance:Number(v)})}/><Field label="ดอกเบี้ยต่อปี (%)" type="number" value={f.annualInterestRate} onChange={v=>setF({...f,annualInterestRate:Number(v)})}/><Field label="ยอดจ่ายต่อเดือน (0 = คำนวณ)" type="number" value={f.monthlyPayment} onChange={v=>setF({...f,monthlyPayment:Number(v)})}/>{auto&&<p className="rounded-xl bg-[#FBF7EF] p-3 text-xs text-muted">ระบบประมาณยอดขั้นต่ำ {money(min)}/เดือน</p>}<Field label="วันกำหนดชำระ" type="number" value={f.paymentDay} onChange={v=>setF({...f,paymentDay:Number(v)})}/></div><button className="btn-primary mt-5 w-full" disabled={!f.name||f.originalPrincipal<=0||f.currentBalance<0} onClick={()=>onSave(f)}>บันทึก</button></Modal>}
function AssetModal({item,month,onClose,onSave}:any){const [f,setF]=useState<Asset>(item||{id:uid(),name:"",type:"house",value:0,financed:true,remainingDebt:0,annualInterestRate:0,monthlyPayment:0,paymentDay:1,status:"active",annualMinimumPayment:0,targetDate:""});const original=item?.originalDebt||f.originalDebt||f.remainingDebt;const calc=assetMonthlyPlan(f,month);useEffect(()=>{if(f.financed&&f.monthlyPayment===0&&calc>0)setF(x=>({...x,monthlyPayment:calc}))},[f.financed,f.monthlyPayment, f.annualMinimumPayment,f.targetDate,month,calc]);return <Modal title={item?"แก้ไขสินทรัพย์":"เพิ่มสินทรัพย์"} onClose={onClose}><div className="space-y-3"><Field label="ชื่อสินทรัพย์" required value={f.name} onChange={v=>setF({...f,name:v})}/><Select label="ประเภท" value={f.type} onChange={v=>setF({...f,type:v as any})} options={[["land","ที่ดิน"],["house","บ้าน"],["car","รถ"]]}/><Field label="มูลค่าทรัพย์สิน" required type="number" value={f.value} onChange={v=>setF({...f,value:Number(v)})}/><Select label="ยังผ่อนอยู่ไหม" value={String(f.financed)} onChange={v=>setF({...f,financed:v==="true"})} options={[["true","ผ่อนอยู่"],["false","ไม่ผ่อน"]]}/>{f.financed&&<><Field label="ยอดหนี้เริ่มต้นของสินทรัพย์" type="number" value={original} onChange={v=>setF({...f,originalDebt:Number(v)})}/><Field label="ยอดหนี้คงเหลือ" type="number" value={f.remainingDebt} onChange={v=>setF({...f,remainingDebt:Number(v)})}/><Field label="ดอกเบี้ยต่อปี (%)" type="number" value={f.annualInterestRate} onChange={v=>setF({...f,annualInterestRate:Number(v)})}/><Field label="ยอดจ่ายต่อเดือน" type="number" value={f.monthlyPayment} onChange={v=>setF({...f,monthlyPayment:Number(v)})}/><Field label="ยอดจ่ายขั้นต่ำต่อปี" type="number" value={f.annualMinimumPayment||0} onChange={v=>setF({...f,annualMinimumPayment:Number(v)})}/><Field label="วันกำหนดชำระ" type="number" value={f.paymentDay} onChange={v=>setF({...f,paymentDay:Number(v)})}/><div className="border-t border-[#EAE1D5] pt-4"><p className="text-sm font-medium">ช่วยคำนวณยอดจ่าย</p><p className="mt-1 text-xs text-muted">วันเป้าหมายใช้สำหรับคำนวณจำนวนเดือนที่เหลือเท่านั้น ไม่ได้นำยอดหนี้คงเหลือมาคำนวณยอดจ่ายต่อเดือน</p><Field label="วันเป้าหมายชำระหมด (ถ้ามี)" type="date" value={f.targetDate||""} onChange={v=>setF({...f,targetDate:v})}/><div className="mt-3 rounded-2xl bg-[#FBF7EF] p-4 text-sm"><p>ระบบแนะนำให้กัน <b>{money(calc)}</b>/เดือน</p>{f.targetDate&&<p className="mt-1 text-xs text-muted">เหลือประมาณ {monthsUntil(f.targetDate,month)} เดือนถึงเป้าหมาย · คำนวณจากยอดขั้นต่ำต่อปี {money(f.annualMinimumPayment||0)}</p>}</div></div></>}</div><button className="btn-primary mt-5 w-full" disabled={!f.name||f.value<=0} onClick={()=>onSave({...f,originalDebt:original})}>บันทึก</button></Modal>}
function InvestmentModal({item,onClose,onSave}:any){const [f,setF]=useState<Investment>(item||{id:uid(),name:"",investmentDay:1,monthlyTarget:0,totalInvested:0});return <Modal title={item?"แก้ไขแหล่งลงทุน":"เพิ่มแหล่งลงทุน"} onClose={onClose}><div className="space-y-3"><Field label="ชื่อแหล่งลงทุน" required value={f.name} onChange={v=>setF({...f,name:v})}/><Field label="วันลงทุน" type="number" value={f.investmentDay} onChange={v=>setF({...f,investmentDay:Number(v)})}/><Field label="ยอดลงทุนต่อเดือน" type="number" value={f.monthlyTarget} onChange={v=>setF({...f,monthlyTarget:Number(v)})}/><Field label="ยอดลงทุนสะสม" type="number" value={f.totalInvested} onChange={v=>setF({...f,totalInvested:Number(v)})}/></div><button className="btn-primary mt-5 w-full" disabled={!f.name} onClick={()=>onSave(f)}>บันทึก</button></Modal>}
function ExpenseModal({item,onClose,onSave}:any){const [f,setF]=useState<Expense>(item||{id:uid(),name:"",plannedAmount:0,paymentDay:1,status:"active"});return <Modal title={item?"แก้ไขค่าใช้จ่าย":"เพิ่มค่าใช้จ่าย"} onClose={onClose}><div className="space-y-3"><Field label="ชื่อรายจ่าย" required value={f.name} onChange={v=>setF({...f,name:v})}/><Field label="ยอดตามแผน" required type="number" value={f.plannedAmount} onChange={v=>setF({...f,plannedAmount:Number(v)})}/><Field label="วันกำหนดจ่าย" type="number" value={f.paymentDay} onChange={v=>setF({...f,paymentDay:Number(v)})}/></div><button className="btn-primary mt-5 w-full" disabled={!f.name||f.plannedAmount<0} onClick={()=>onSave(f)}>บันทึก</button></Modal>}
function SavingModal({item,month,onClose,onSave}:any){const [f,setF]=useState<SavingGoal>(item||{id:uid(),name:"",targetAmount:0,currentAmount:0,monthlyAmount:0,targetDate:"",paymentDay:1,status:"active"});const auto=f.monthlyAmount<=0;const calc=auto?goalMonthlyPlan(f.targetAmount,f.currentAmount,f.targetDate,month):f.monthlyAmount;const months=f.targetDate?monthsUntil(f.targetDate,month):0;const remaining=Math.max(0,f.targetAmount-f.currentAmount);return <Modal title={item?"แก้ไขเป้าหมาย":"เพิ่มเป้าหมาย"} onClose={onClose}><div className="space-y-3"><Field label="ชื่อเป้าหมาย" required value={f.name} onChange={v=>setF({...f,name:v})}/><Field label="ยอดเป้าหมาย" required type="number" value={f.targetAmount} onChange={v=>setF({...f,targetAmount:Number(v)})}/><Field label="ยอดสะสมปัจจุบัน" type="number" value={f.currentAmount} onChange={v=>setF({...f,currentAmount:Number(v)})}/><Field label="ยอดเก็บต่อเดือน (0 = คำนวณอัตโนมัติ)" type="number" value={f.monthlyAmount} onChange={v=>setF({...f,monthlyAmount:Number(v)})}/><Field label="วันเก็บเงิน" type="number" value={f.paymentDay} onChange={v=>setF({...f,paymentDay:Number(v)})}/><Field label="วันเป้าหมาย" type="date" value={f.targetDate||""} onChange={v=>setF({...f,targetDate:v})}/>{f.targetDate&&<div className="rounded-xl bg-[#FBF7EF] p-3 text-sm"><p>ยอดที่ต้องเก็บคงเหลือ <b>{money(remaining)}</b></p><p className="mt-1">เดือนนี้ต้องกัน <b>{money(calc)}</b></p><p className="mt-1 text-xs text-muted">เหลือประมาณ {months} เดือนถึงวันเป้าหมาย · คำนวณจากยอดคงเหลือ ÷ จำนวนเดือน</p></div>}</div><button className="btn-primary mt-5 w-full" disabled={!f.name||f.targetAmount<=0} onClick={()=>onSave(f)}>บันทึก</button></Modal>}
function InsuranceModal({item,onClose,onSave}:any){const [f,setF]=useState<Insurance>(item||{id:uid(),company:"",insuredName:"",beneficiary:"",lifeCoverage:0,accidentCoverage:0,criticalIllnessCoverage:0,hospitalDailyCoverage:0,medicalCoverage:0,premiumAmount:0,premiumDay:1,other:[]});return <Modal title={item?"แก้ไขประกัน":"เพิ่มประกัน"} onClose={onClose}><div className="space-y-3"><Field label="บริษัทประกัน" required value={f.company} onChange={v=>setF({...f,company:v})}/><Field label="ชื่อผู้เอาประกัน" value={f.insuredName} onChange={v=>setF({...f,insuredName:v})}/><Field label="เบี้ยประกัน" type="number" value={f.premiumAmount} onChange={v=>setF({...f,premiumAmount:Number(v)})}/><Field label="วันกำหนดจ่าย" type="number" value={f.premiumDay} onChange={v=>setF({...f,premiumDay:Number(v)})}/></div><button className="btn-primary mt-5 w-full" disabled={!f.company} onClick={()=>onSave(f)}>บันทึก</button></Modal>}
function PaymentModal({p,onClose,onSave}:{p:Payment;onClose:()=>void;onSave:(p:Payment,a:number,n:string)=>void}){const [a,setA]=useState(String(p.actualAmount??p.plannedAmount)),[note,setNote]=useState(p.note||"");return <Modal title={p.status==="paid"?"แก้ไขยอดที่จ่าย":"ยืนยันว่าจ่ายแล้ว"} onClose={onClose}><div className="space-y-3"><Field label="ยอดจ่ายจริง" type="number" value={a} onChange={setA}/><label className="block"><span className="text-sm text-muted">หมายเหตุ (ไม่บังคับ)</span><textarea className="input mt-2 min-h-24" value={note} onChange={e=>setNote(e.target.value)} placeholder="เช่น ยอดจริงต่างจากแผนเพราะ..."/></label></div><button className="btn-primary mt-5 w-full" onClick={()=>onSave(p,Number(a)||0,note)}>ยืนยัน</button></Modal>}
